INSERT INTO EMPLOYEE (NAME, SALARY, DEPARTMENT) VALUES ('John Doe', 100, 'RnD');
INSERT INTO EMPLOYEE (NAME, SALARY, DEPARTMENT) VALUES ('Alice Van', 150, 'IT');
INSERT INTO EMPLOYEE (NAME, SALARY, DEPARTMENT) VALUES ('Steve Richards', 200, 'HR');